package ytuce.gp.mfmsp.Constants;

public enum AccessTokenName {
    META_ACCESS_TOKEN, META_PAGE_ID, TELEGRAM_BOT_TOKEN, TELEGRAM_BOT_USERNAME,
    TWITTER_ACCOUNT_ID, TWITTER_BEARER_TOKEN, TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET,
    TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET
}
